ROM ubuntu as initial
RUN rm -rf /usr/share/ /var/cache /var/lib/dpkg /usr/games /usr/lib32 /usr/local /opt /var/log /usr/libx32 /bin /sbin /usr/bin /usr/sbin /var/spool 

FROM scratch
COPY --from=initial / /
WORKDIR /app/
COPY ./flying-squirrel-tactix /fsql
COPY ./.env /app/.env
COPY ./cert.pem /app/cert.pem
COPY ./privkey.pem /app/privkey.pem
EXPOSE 443
CMD ["/fsql"]
